const FIELD_LABELS = {
  fullName: 'Name',
  fatherName: "Father's name",
  motherName: "Mother's name",
  birthDate: 'Birth date',
  bloodGroup: 'Blood group',
  gender: 'Gender',
  nid: 'NID',
  destinationCountry: 'Country',
  employer: 'Employer',
  passportNumber: 'Passport no',
  passportIssueDate: 'Passport issue date',
  passportExpiryDate: 'Passport expiry date',
  visaNo: 'Visa no',
  visaIssueDate: 'Visa issue date',
  visaExpiryDate: 'Visa expiry date',
  referralNo: 'Referral no',
  bmetId: 'BMET no',
  clearanceId: 'EC no',
  clearanceDate: 'EC date',
  rlId: 'License no',
  recruitingAgencyName: 'Recruiting agency name',
  recruitingAgencyPhone: 'Recruiting agency phone',
  addressHouseVillageRoad: 'House/Vill/Road',
  addressPostOffice: 'Post office',
  addressPoliceStation: 'Police station',
  addressUpazila: 'Upazila',
  addressDistrict: 'District',
  addressDivision: 'Division',
  emergencyContactName: 'Emergency contact name',
  emergencyContactRelation: 'Emergency contact relation',
  emergencyContactMobile: 'Emergency contact mobile',
  emergencyContactAddress: 'Emergency contact address',
};

const getFieldLabel = (field) => FIELD_LABELS[field] || field;

module.exports = { FIELD_LABELS, getFieldLabel };
